# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 711872a1f8a6afffb783e1e98eb9552eb6c8dd54b155f1e8a6ba20b44885e61999e3b1b1f782a9642850fe406692d7a59a7886b8dab2fde591259a193bbadf26

test:
  secret_key_base: 1c48a29f16f645bfa051a403f42be312908583a2e002e9b0d333ae07f68425e39fbcf279cdb1a25f5ba243a3023c19fa6d8cc93d70ab9dcccb41d71c0ebc1f36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
